vagrant:
  ip: '192.168.12.19'
  hostname: 'libertysoil.dev'

ssh_users:
  - ssh_user_name: 'deploy'
    ssh_user_pass: 'no' #put 'no' to lock user
    ssh_user_can_sudo: true
  - ssh_user_name: 'lsadmin'
    ssh_user_pass: 'lsadmin1234'
    ssh_user_can_sudo: true
  - ssh_user_name: 'dev'
    ssh_user_pass: 'dev1234'
    ssh_user_can_sudo: false
    
apache_modules:
  - 'alias'
  - 'proxy'
  - 'proxy_connect'
  - 'proxy_ftp'
  - 'proxy_http'
  - 'proxy_fcgi'
  - 'proxy_scgi'
  - 'proxy_wstunnel'
  - 'proxy_ajp'
  - 'proxy_balancer'
  - 'proxy_express'
  - 'rewrite'
  - 'vhost_alias'
    
sites:
  - site_name: 'libertysoil'
    local_path: '../libertysoil-site' # Relative to Vagrantfile location
    remote_path: '/var/www/libertysoil'
    enabled: true
    log_level: 'debug'
    host: 'libertysoil.dev'
    aliases:
      - 'www.libertysoil.dev'
      - 'ww2.libertysoil.dev'
    